# Instructor Do: Decision Trees

In [1]:
# At the top of this decision tree is the root node or the parent node. The root node represents the entire population. This node gets divided into two or more homogeneous sets in our decision tree to answer the questions which is a branch or subsection of the tree. When we divide a node into two or more subnodes, it's called splitting.

# When we split the root node into two subnodes, they are called child nodes which split again into subnodes if another question in them (decision node). The four results do not split further and are referred to as a leaf or terminal node.

In [2]:
#Decision trees, as you have seen, are like a series of if-else statements. But how does a decision tree determine which if-else statement to use first? In other words, how does it decide on the root node?

In [3]:
# Initial imports
import pandas as pd
from path import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [4]:
# Our goal is to predict if a loan application is worthy of approval based on information we have in our df_loans DataFrame.

## Loading and Preprocessing Loans Encoded Data

In [5]:
# Loading data
file_path = Path("../Resources/loans_data_encoded.csv")
df_loans = pd.read_csv(file_path)
df_loans.head()

,amount,term,age,bad,month_num,education_Bachelor,education_High School or Below,education_Master or Above,education_college,gender_female,gender_male
0,1000,30,45,0,6,0,1,0,0,0,1
1,1000,30,50,0,7,1,0,0,0,1,0
2,1000,30,33,0,8,1,0,0,0,1,0
3,1000,15,27,0,9,0,0,0,1,0,1
4,1000,30,28,0,10,0,0,0,1,1,0

In [6]:
# Define features set
X = df_loans.copy()
X = X.drop("bad", axis=1)
X.head()

,amount,term,age,month_num,education_Bachelor,education_High School or Below,education_Master or Above,education_college,gender_female,gender_male
0,1000,30,45,6,0,1,0,0,0,1
1,1000,30,50,7,1,0,0,0,1,0
2,1000,30,33,8,1,0,0,0,1,0
3,1000,15,27,9,0,0,0,1,0,1
4,1000,30,28,10,0,0,0,1,1,0

In [7]:
#The target set is the bad column, indicating whether or not a loan application is good (0) or bad (1).

In [8]:
# Define target vector
y = df_loans["bad"].values.reshape(-1, 1)
y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [9]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [10]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(375, 10)
(125, 10)
(375, 1)
(125, 1)

In [11]:
#We can manually specify the desired split with the train_size parameter.

In [12]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, random_state=78, train_size=0.80)

In [13]:
print(X_train2.shape)
print(X_test2.shape)
print(y_train2.shape)
print(y_test2.shape)

(400, 10)
(100, 10)
(400, 1)
(100, 1)

In [14]:
#By default, our training and testing data sets are 75% and 25%, respectively, of the original data. Using the following code, we can see the data's 75-25 split.

#The output from running the code above shows that the X_train and y_train is 75% of 500 and that the X_test and y_test are 25%.

In [15]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [16]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [17]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Fitting the Decision Tree Model

In [18]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()

In [19]:
# Fitting the model
model = model.fit(X_train_scaled, y_train)

## Making Predictions Using the Tree Model

In [20]:
# Making predictions using the testing data
predictions = model.predict(X_test_scaled)

In [21]:
#The output from this code will be an array of 125 predictions with either a 1 for a bad loan application or a 0 for a good, or approved, loan application.

In [22]:
predictions

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0])

## Model Evaluation

In [24]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

cm_df

          Predicted 0  Predicted 1
Actual 0           52           32
Actual 1           21           20

In [25]:
# The CM results show that:

# Out of 84 good loan applications (Actual 0), 52 were predicted to be good (Predicted 0), which we call true positives.
# Out of 84 good loan applications (Actual 0), 32 were predicted to be bad (Predicted 1), which are considered false negatives.
# Out of 41 bad loan applications (Actual 1), 21 were predicted to be good (Predicted 0) and are considered false positives.
# Out of 41 bad loan applications (Actual 1), 20 were predicted to be bad (Predicted 1) and are considered true negatives.

In [26]:
# 0 - good
# 1 - bad

In [27]:
# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [28]:
acc_score

0.576

In [35]:
#(True Positives (TP) + True Negatives (TN)) / Total = (52 + 20)/125
x = cm_df["Predicted 0"][0]+cm_df["Predicted 1"][1]
total = cm_df["Predicted 0"][0]+cm_df["Predicted 1"][1]+cm_df["Predicted 0"][1]+cm_df["Predicted 1"][0]
y = x/total
y

0.576

In [36]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           52           32
Actual 1           21           20

Accuracy Score : 0.576
Classification Report
              precision    recall  f1-score   support

           0       0.71      0.62      0.66        84
           1       0.38      0.49      0.43        41

    accuracy                           0.58       125
   macro avg       0.55      0.55      0.55       125
weighted avg       0.60      0.58      0.59       125

In [37]:
# Let's go over the results in the classification report:

# Precision: Precision is the measure of how reliable a positive classification is. From our results, the precision for the good loan applications can be determined by the ratio TP/(TP + FP), which is 52/(52 + 21) = 0.71. The precision for the bad loan applications can be determined as follows: 20/(20 + 33) = 0.38. A low precision is indicative of a large number of false positives. Of the 52 loan applications we predicted to be bad applications, 32 were actually good loan applications.
# Recall: Recall is the ability of the classifier to find all the positive samples. It can be determined by the ratio: TP/(TP + FN), or 52/(52 + 32) = 0.62 for the good loans and 20/(21 + 20) = 0.49 for the bad loans. A low recall is indicative of a large number of false negatives.
# F1 score: F1 score is a weighted average of the true positive rate (recall) and precision, where the best score is 1.0 and the worst is 0.0.
# Support: Support is the number of actual occurrences of the class in the specified dataset. For our results, there are 84 actual occurrences for the good loans and 41 actual occurrences for bad loans.
# In summary, this model may not be the best one for preventing fraudulent loan applications because the model's accuracy, 0.576, is low, and the precision and recall are not good enough to state that the model will be good at classifying fraudulent loan applications. Modeling is an iterative process: you may need more data, more cleaning, another model parameter, or a different model. It's also important to have a goal that's been agreed upon, so that you know when the model is good enough.